FROM oven/bun:1


WORKDIR /app
# Copy package.json and package-lock.json
COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web
# Install dependencies





RUN bun install
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build


EXPOSE 8000

CMD ["bun","run","start:web"]


